# Generated by Django 5.0.6 on 2024-06-08 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id_hospital', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_hospital', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_insumo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('lote', models.CharField(max_length=255)),
                ('cantidad_entrada', models.IntegerField(default=0)),
                ('cantidad_salida', models.IntegerField(default=0)),
                ('existencia', models.IntegerField(default=0)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_entrada', models.DateField()),
                ('id_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hospital')),
                ('id_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.insumo')),
            ],
        ),
    ]
