# Generated by Django 5.0.6 on 2024-07-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='TC',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='codigo_cup',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='importado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='produccion_nacional',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
