# Generated by Django 5.0.6 on 2024-07-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_insumo_tc_insumo_codigo_cup_insumo_importado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='cobertura',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='codigo_cup',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
