# Generated by Django 5.0.6 on 2024-07-17 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_inventario_cobertura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='cobertura',
        ),
    ]
