# Generated by Django 5.0.6 on 2024-07-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_inventario_cobertura'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='cobertura',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
